package app.byshawn.nib.overlay;

import android.app.*;
import android.content.*;
import android.content.pm.ServiceInfo;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.net.Uri;
import android.os.*;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import java.util.*;

public class NibWakeService extends Service {
 public static final String ACTION_START="app.byshawn.nib.WAKE_START",ACTION_CONFIG="app.byshawn.nib.WAKE_CONFIG",ACTION_STOP="app.byshawn.nib.WAKE_STOP",BROADCAST_WAKE="app.byshawn.nib.WAKE_ANIMATION";
 private static final String PREFS="nib_overlay",CHANNEL="nib_wake",ACK_ID="nib-wake-ack";private static final int NOTIFICATION_ID=7332;
 private Handler handler;private SpeechRecognizer recognizer;private TextToSpeech tts;private boolean ttsReady=false,commandMode=false,destroyed=false,listening=false,ignoreNextError=false,waitingForCommandStart=false;private long commandStartedAt=0L;private PowerManager.WakeLock wakeLock;private final Random random=new Random();
 private final String[] replies={"Yeah?","What's up?","Mm-hm?","I'm listening.","Go for it.","You rang?"};
 private final Runnable wakeRestartTask=()->{if(!destroyed){commandMode=false;waitingForCommandStart=false;startListening(false);}};
 @Override public void onCreate(){super.onCreate();handler=new Handler(Looper.getMainLooper());tts=new TextToSpeech(getApplicationContext(),status->{ttsReady=status==TextToSpeech.SUCCESS;if(ttsReady){tts.setSpeechRate(1.04f);tts.setPitch(1.08f);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onError(String id){if(ACK_ID.equals(id))handler.post(()->beginCommandListening());}public void onDone(String id){if(ACK_ID.equals(id))handler.postDelayed(()->beginCommandListening(),90);}});}});PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null){wakeLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"Nib::WakeWord");wakeLock.setReferenceCounted(false);wakeLock.acquire();}handler.post(this::createRecognizer);}
 @Override public int onStartCommand(Intent intent,int flags,int startId){String action=intent==null?ACTION_START:intent.getAction();android.content.SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);String mode=p.getString("wakeMode","off");if(ACTION_STOP.equals(action)||"off".equals(mode)||("running".equals(mode)&&!p.getBoolean("enabled",false))){if(ACTION_STOP.equals(action))p.edit().putString("wakeMode","off").apply();stopSelf();return START_NOT_STICKY;}ensureForeground();if(ACTION_CONFIG.equals(action)){refreshNotification();restartWakeSoon(160);}else restartWakeSoon(220);return START_STICKY;}
 private void createRecognizer(){if(destroyed||recognizer!=null)return;try{if(Build.VERSION.SDK_INT>=31&&SpeechRecognizer.isOnDeviceRecognitionAvailable(this))recognizer=SpeechRecognizer.createOnDeviceSpeechRecognizer(this);else recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(listener);}catch(Exception e){stopSelf();}}
 private final RecognitionListener listener=new RecognitionListener(){public void onReadyForSpeech(Bundle p){listening=true;}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){listening=false;}public void onError(int error){listening=false;if(destroyed)return;if(ignoreNextError){ignoreNextError=false;return;}if(waitingForCommandStart)return;if(commandMode){if(System.currentTimeMillis()-commandStartedAt<8500L&&(error==SpeechRecognizer.ERROR_NO_MATCH||error==SpeechRecognizer.ERROR_SPEECH_TIMEOUT||error==SpeechRecognizer.ERROR_RECOGNIZER_BUSY)){handler.postDelayed(()->startListening(true),error==SpeechRecognizer.ERROR_RECOGNIZER_BUSY?600:220);}else returnToWake();}else handler.postDelayed(()->startListening(false),error==SpeechRecognizer.ERROR_RECOGNIZER_BUSY?650:260);}public void onResults(Bundle results){listening=false;ArrayList<String> list=results==null?null:results.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(commandMode){if(waitingForCommandStart)return;String cmd=firstText(list);if(cmd.isEmpty())returnToWake();else deliverCommand(cmd);return;}if(containsWake(list))activateWake();else restartWakeSoon(220);}public void onPartialResults(Bundle partial){if(commandMode||destroyed)return;ArrayList<String> list=partial==null?null:partial.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(containsWake(list))activateWake();}public void onEvent(int type,Bundle params){}};
 private Intent recognitionIntent(boolean command){Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,!command);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5);i.putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault().toLanguageTag());return i;}
 private void startListening(boolean command){if(destroyed)return;if(recognizer==null){createRecognizer();handler.postDelayed(()->startListening(command),300);return;}try{if(listening){ignoreNextError=true;recognizer.cancel();}commandMode=command;waitingForCommandStart=false;if(command)commandStartedAt=System.currentTimeMillis();recognizer.startListening(recognitionIntent(command));}catch(Exception e){handler.postDelayed(()->startListening(command),500);}}
 private void restartWakeSoon(long delay){handler.removeCallbacks(wakeRestartTask);handler.postDelayed(wakeRestartTask,delay);}
 private boolean containsWake(ArrayList<String> list){if(list==null)return false;String phrase=normalize(getSharedPreferences(PREFS,MODE_PRIVATE).getString("wakePhrase","Hey Nib"));for(String s:list){String n=normalize(s);if(n.contains(phrase)||("hey nib".equals(phrase)&&(n.contains("hey nip")||n.contains("hey neb"))))return true;}return false;}
 private String normalize(String s){return s==null?"":s.toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ").replaceAll("\\s+"," ").trim();}
 private String firstText(ArrayList<String> list){if(list==null)return "";for(String s:list)if(s!=null&&!s.trim().isEmpty())return s.trim();return "";}
 private void activateWake(){if(commandMode||destroyed)return;commandMode=true;waitingForCommandStart=true;listening=false;try{if(recognizer!=null){ignoreNextError=true;recognizer.cancel();}}catch(Exception ignored){}sendBroadcast(new Intent(BROADCAST_WAKE).setPackage(getPackageName()));String mode=getSharedPreferences(PREFS,MODE_PRIVATE).getString("wakeAckMode","speak");if("silent".equals(mode)){handler.postDelayed(this::beginCommandListening,160);return;}if("sound".equals(mode)){try{ToneGenerator tone=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,55);tone.startTone(ToneGenerator.TONE_PROP_BEEP,120);handler.postDelayed(tone::release,180);}catch(Exception ignored){}handler.postDelayed(this::beginCommandListening,250);return;}String line=replies[random.nextInt(replies.length)];if(ttsReady)tts.speak(line,TextToSpeech.QUEUE_FLUSH,null,ACK_ID);else handler.postDelayed(this::beginCommandListening,220);}
 private void beginCommandListening(){if(destroyed)return;waitingForCommandStart=false;commandMode=true;commandStartedAt=System.currentTimeMillis();startListening(true);}
 private void deliverCommand(String cmd){android.content.SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);p.edit().putString("pendingVoiceCommand",cmd).putLong("pendingVoiceAt",System.currentTimeMillis()).apply();sendBroadcast(new Intent(BROADCAST_WAKE).setPackage(getPackageName()).putExtra("commandReady",true));boolean overlayEnabled=p.getBoolean("enabled",false);if(overlayEnabled){try{Intent panel=new Intent(this,NibPanelActivity.class);panel.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_NO_ANIMATION);panel.putExtra("panelUrl",panelUrl(p.getString("url","")));startActivity(panel);}catch(Exception ignored){launchMain();}}else launchMain();returnToWake();}
 private String panelUrl(String overlay){try{Uri u=Uri.parse(overlay);if(u.getScheme()!=null&&u.getAuthority()!=null)return u.getScheme()+"://"+u.getAuthority()+"/?nibPanel=1";}catch(Exception ignored){}return "https://nib-companion.floot.app/?nibPanel=1";}
 private void launchMain(){Intent launch=getPackageManager().getLaunchIntentForPackage(getPackageName());if(launch!=null){launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);launch.putExtra("nibVoiceCommandReady",true);try{startActivity(launch);}catch(Exception ignored){}}}
 private void returnToWake(){waitingForCommandStart=false;commandMode=false;commandStartedAt=0L;handler.postDelayed(()->startListening(false),420);}
 private void ensureForeground(){Notification n=buildNotification();if(Build.VERSION.SDK_INT>=29)startForeground(NOTIFICATION_ID,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);else startForeground(NOTIFICATION_ID,n);}
 private Notification buildNotification(){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Hey Nib wake listening",NotificationManager.IMPORTANCE_LOW);c.setDescription("Listens on-device for Nib's wake phrase");c.setShowBadge(false);nm.createNotificationChannel(c);}Intent stop=new Intent(this,NibWakeService.class).setAction(ACTION_STOP);PendingIntent spi=PendingIntent.getService(this,7333,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent open=getPackageManager().getLaunchIntentForPackage(getPackageName());PendingIntent opi=open==null?null:PendingIntent.getActivity(this,7334,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String phrase=getSharedPreferences(PREFS,MODE_PRIVATE).getString("wakePhrase","Hey Nib");Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(R.drawable.ic_nib_status).setContentTitle("Nib is listening for “"+phrase+"”").setContentText(Build.VERSION.SDK_INT>=31&&SpeechRecognizer.isOnDeviceRecognitionAvailable(this)?"Wake detection stays on this phone":"Using Android's speech recognizer").setOngoing(true).setOnlyAlertOnce(true).setCategory(Notification.CATEGORY_SERVICE).setPriority(Notification.PRIORITY_LOW).addAction(new Notification.Action.Builder(0,"Stop listening",spi).build());if(opi!=null)b.setContentIntent(opi);return b.build();}
 private void refreshNotification(){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.notify(NOTIFICATION_ID,buildNotification());}
 @Override public void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);try{if(recognizer!=null){recognizer.cancel();recognizer.destroy();}}catch(Exception ignored){}if(tts!=null)tts.shutdown();if(wakeLock!=null&&wakeLock.isHeld())wakeLock.release();super.onDestroy();}
 @Override public IBinder onBind(Intent intent){return null;}
}
